name: New Fault Mechanism Required
description: Create issues with this template to request a new fault mechanism for ITBench.
title: "[New Fault Mechanism]: "
labels: ["enhancement", "New Incident"]
projects: ["IT-Automation-Testbed"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        To help support a rapid review process, please fill in as much detail as possible.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Who are the primary contacts for this request?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: target-area
    attributes:
      label: What area of the deployment will be most affected?
      default: 0
      options:
        - Container / Pod
        - Network
        - Node
  - type: checkboxes
    id: target-applications
    attributes:
      label: To which sample applications will this apply
      options:
        - label: "otel_astronomy_shop"
        - label: "dsb_hotel_reservation"
  - type: textarea
    id: mechanism-description
    attributes:
      label: Description of the fault mechanism to be added
      description: What new mechanism is requird?
      placeholder: What new faults will be observed, and how will they be created?
    validations:
      required: true
  - type: textarea
    id: mechanism-advantages
    attributes:
      label: What scenario support is unlocked as a result of this new mechanism being added?
      placeholder: Describe in detail the failure mode that requires this new mechanism to be simulated.
    validations:
      required: true
  - type: textarea
    id: similar-mechanisms
    attributes:
      label: Do similar mechanisms already exist?  How is this different?
      placeholder: |
        Yes.  [run_chaos_cpu_stress](https://github.ibm.com/DistributedCloudResearch/IT-Automation-Testbed/blob/main/roles/fault_injection/tasks/run_chaos_cpu_stress.yaml)
        is similar, but while that simulates a busy CPU, this will overload the GPU.
    validations:
      required: true
  - type: textarea
    id: external-libraries
    attributes:
      label: What (if any) new external libraries are required?
      placeholder: Please list all external libraries that will be required, including repository URL and exact version number.
    validations:
      required: true
  - type: input
    id: pull-request
    attributes:
      label: Pull Request
      description: Link to PR that will deliver this mechanism
      placeholder: https://github.ibm.com/DistributedCloudResearch/IT-Automation-Testbed/pull/12345
    validations:
      required: false
  - type: textarea
    id: representative-gif
    attributes:
      label: What GIF best presents how you feel about this new mechanism?
      value: |
        ![Surprised and Excited](https://media.giphy.com/media/gVE7nURcnD9bW/giphy.gif?cid=ecf05e477zw0vj8uaas9zxs74174n6fdbgnndbwssv0ae1mx&ep=v1_gifs_search&rid=giphy.gif&ct=g)
