---
- name: Create deployment record
  set_fact:
    assertion_json:
      status:
        conditions:
          - type: Deployed
            status: False
            lastTransitionTime: "{{ now(utc=True, fmt='%Y-%m-%dT%H:%M:%SZ') }}"
  when: sre_bench_runner
  tags:
    - capture_failed_deployment_state

- name: Create a JSON with application deployment details
  copy:
    content: "{{ assertion_json | to_json | indent(2) }}"
    dest: "/tmp/assertion.json"
    mode: "0644"
  when: sre_bench_runner
  tags:
    - capture_failed_deployment_state

- name: Upload the JSON with application deployment details to S3
  amazon.aws.s3_object:
    endpoint_url: "https://s3.us-east-2.amazonaws.com"
    bucket: "{{ s3_bucket_name_for_results }}"
    object: "/{{ sre_agent_name__version_number }}/{{run_uuid}}/{{scenario_number}}/{{run_number}}/assertion.json"
    src: "/tmp/assertion.json"
    mode: put
  when:
    - sre_bench_runner
    - run_uuid is defined and scenario_number is defined and run_number is defined
  tags:
    - capture_failed_deployment_state
