---    
- name: Record Deployment time
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: bundle-alert-timestamps
        namespace: "{{ otel_astronomy_app_namespace_project_name }}"
      data:
        deployment_time: "{{ now(utc=True, fmt='%Y-%m-%dT%H:%M:%SZ') }}"
  tags:
    - install_sample_applications
  when:
    - sample_application == "otel_astronomy_shop"

- name: Record Deployment time
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: bundle-alert-timestamps
        namespace: "{{ deathstarbench_hotelreservation_app_namespace_project_name }}"
      data:
        deployment_time: "{{ now(utc=True, fmt='%Y-%m-%dT%H:%M:%SZ') }}"
  tags:
    - install_sample_applications
  when:
    - sample_application == "dsb_hotel_reservation"

- name: Create deployment record
  set_fact:
    assertion_json:
      status:
        conditions:
          - type: Deployed
            status: True
            lastTransitionTime: "{{ now(utc=True, fmt='%Y-%m-%dT%H:%M:%SZ') }}"
  tags:
    - install_sample_applications
  when:
    - sre_bench_runner

- name: Create a JSON with application deployment details
  copy:
    content: "{{ assertion_json | to_json | indent(2) }}"
    dest: "/tmp/assertion.json"
    mode: "0644"
  tags:
    - install_sample_applications
  when:
    - sre_bench_runner

- name: Upload the JSON with application deployment details to S3
  amazon.aws.s3_object:
    endpoint_url: "https://s3.us-east-2.amazonaws.com"
    bucket: "{{ s3_bucket_name_for_results }}"
    object: "/{{ sre_agent_name__version_number }}/{{run_uuid}}/{{scenario_number}}/{{run_number}}/assertion.json"
    src: "/tmp/assertion.json"
    mode: put
  tags:
    - install_sample_applications
  when:
    - sre_bench_runner
    - run_uuid is defined and scenario_number is defined and run_number is defined
