---
- import_tasks: setup_awx.yaml
- import_tasks: configure_awx.yaml
- import_tasks: job_template_setup.yaml
- import_tasks: workflow_setup.yaml
- import_tasks: workflow_three_stages_setup.yaml
- import_tasks: runner_workflow_setup.yaml
- import_tasks: launch_workflow.yaml
