---
- name: Add Helm chart repo for Ansible AWX
  kubernetes.core.helm_repository:
    name: awx-operator
    kubeconfig_path: "{{ awx_kubeconfig }}"
    repo_url: "https://ansible-community.github.io/awx-operator-helm"
  tags:
    - awx_setup

- name: Update Helm repo
  kubernetes.core.helm:
    name: dummy
    kubeconfig_path: "{{ awx_kubeconfig }}"
    release_namespace: awx
    state: absent
    update_repo_cache: true
  tags:
    - awx_setup

- name: Install the AWX operator
  kubernetes.core.helm:
    name: "awx-operator"
    kubeconfig_path: "{{ awx_kubeconfig }}"
    chart_ref: awx-operator/awx-operator
    chart_version: "{{ awx_chart_version }}"
    release_namespace: "awx"
    release_state: present
    create_namespace: true
    wait: true
  tags:
    - awx_setup

- name: Deploy AWX
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ awx_kubeconfig }}"
    definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx-deployment
        namespace: awx
      spec:
        service_type: loadbalancer
        postgres_data_volume_init: true
        postgres_init_container_commands: |
          chown 26:0 /var/lib/pgsql/data
          chmod 700 /var/lib/pgsql/data
  tags:
    - awx_setup
