---
- name: Tasks associated with workflow handshake
  ansible.builtin.include_tasks:
    file: workflow_handshake.yaml
    apply:
      tags:
        - workflow_setup_stage_one
        - workflow_setup_stage_two
        - workflow_setup_stage_three
  tags:
    - workflow_setup_stage_one
    - workflow_setup_stage_two
    - workflow_setup_stage_three

- name: Create a workflow job template with workflow nodes in template - stack setup - stage one
  awx.awx.workflow_job_template:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    name: "Scenario-{{scenario_number}}-One-Mode-Deployment-Stage-One"
    inventory: Demo Inventory
    extra_vars: {'run_uuid': 'run_uuid', 'scenario_number': -1, 'run_number': -1, 'sre_agent_name__version_number': 'sre_agent_name__version_number'}
    ask_variables_on_launch: true
    state: "{{ state }}"
    workflow_nodes:
      - identifier: node-install-observability-stack
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--InstallObservability-Stack"
          type: job_template
        related:
          success_nodes:
            - identifier: node-install-sample-application
          failure_nodes:
            - identifier: node-capture-failed-deployment
          always_nodes: []
      - identifier: node-install-sample-application
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Install-Sample-Application-{{ sample_application }}"
          type: job_template
        related:
          success_nodes:
            - identifier: node-telemetry-access
          failure_nodes:
            - identifier: node-capture-failed-deployment
          always_nodes: []
      - identifier: node-telemetry-access
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Setup-For-Telemetry-Access"
          type: job_template
        related:
          success_nodes:
            - identifier: node-trace-gathering
          failure_nodes:
            - identifier: node-capture-failed-deployment
      - identifier: node-trace-gathering
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Trace-Gathering"
          type: job_template
        related:
          success_nodes:
            - identifier: node-trigger-fault
          failure_nodes:
            - identifier: node-capture-failed-deployment
          always_nodes: []
      - identifier: node-trigger-fault
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Trigger-Fault"
          type: job_template
        related:
          success_nodes:
            - identifier: node-post-fault-injection
          failure_nodes:
            - identifier: node-capture-failed-deployment
          always_nodes: []
      - identifier: node-post-fault-injection
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Post-Fault-Injection"
          type: job_template
        related:
          success_nodes:
            - identifier: node-check-for-alerts
          failure_nodes:
            - identifier: node-capture-failed-deployment
          always_nodes: []
      - identifier: node-check-for-alerts
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Check-for-Alerts"
          type: job_template
        related:
          success_nodes:
            - identifier: node-alert-recorder-on
          failure_nodes:
            - identifier: node-capture-failed-deployment
          always_nodes: []
      - identifier: node-alert-recorder-on
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Alert-Recorder-On"
          type: job_template
        related:
          success_nodes:
            - identifier: node-handover-to-agent
          failure_nodes:
            - identifier: node-capture-failed-deployment
          always_nodes: []
      - identifier: node-handover-to-agent
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Handover-To-Agent"
          type: job_template
        related:
          success_nodes: []
          failure_nodes:
            - identifier: node-capture-failed-deployment
          always_nodes: []
      - identifier: node-capture-failed-deployment
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Capture-Failed-Deployment"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes: []
  register: one_mode_deployment_stage_one_result
  tags:
    - workflow_setup_stage_one

- name: Create a workflow job template - stage two - evaluation step
  awx.awx.workflow_job_template:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    name: "Scenario-{{scenario_number}}-One-Mode-Deployment-Stage-Two"
    inventory: Demo Inventory
    extra_vars: {'run_uuid': 'run_uuid', 'scenario_number': -1, 'run_number': -1, 'sre_agent_name__version_number': 'sre_agent_name__version_number'}
    ask_variables_on_launch: true
    state: "{{ state }}"
    workflow_nodes:
      - identifier: node-handover-from-agent
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Handover-From-Agent"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes:
            - node-pre-fault-removal
      - identifier: node-pre-fault-removal
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Pre-Fault-Removal"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes:
            - identifier: node-evaluation
      - identifier: node-evaluation
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Evaluation"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes: []
  register: one_mode_deployment_stage_two_result
  tags:
    - workflow_setup_stage_two

- name: Create a workflow job template - stage three - from pre-fault-removal to removal
  awx.awx.workflow_job_template:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    name: "Scenario-{{scenario_number}}-One-Mode-Deployment-Stage-Three"
    inventory: Demo Inventory
    extra_vars: {'run_uuid': 'run_uuid', 'scenario_number': -1, 'run_number': -1, 'sre_agent_name__version_number': 'sre_agent_name__version_number'}
    ask_variables_on_launch: true
    state: "{{ state }}"
    workflow_nodes:
      - identifier: node-remove-fault
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Remove-Fault"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes:
            - identifier: node-alert-recorder-off
      - identifier: node-alert-recorder-off
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Alert-Recorder-Off"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes:
            - identifier: node-uninstall-sample-application-end
      - identifier: node-uninstall-sample-application-end
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--Uninstall-Sample-Application-{{ sample_application }}"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes:
            - identifier: node-uninstall-observability-stack-end
      - identifier: node-uninstall-observability-stack-end
        unified_job_template:
          name: "Scenario-{{ scenario_number }}--UninstallObservability-Stack"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes: []
  register: one_mode_deployment_stage_three_result
  tags:
    - workflow_setup_stage_three
