fault_injection_documentation_schema:
  type: array
  items:
    type: object
    properties:
      "id":
        type: integer
      "name":
        type: string
      "author":
        type: string
      "description":
        type: string
      "application":
        type: string
        enum: ['otel_astronomy_shop', 'deathstarbench_hotel_reservations', 'Other', 'All']
      "fault_type":
        type: string
        enum: ['FlagD', 'ChaosMesh', 'Custom']
      "required_fields":
        type: array
        items:
          type: string
    additionalProperties: false
    required: ["id", "name", "author", "description", "application", "fault_type", "required_fields"]
