apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-to-prometheus
  namespace: otel-demo
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: metrics
  selector:
    matchLabels:
      component: standalone-collector
