---
- name: Remove / Delete existing Chaos experiments
  ansible.builtin.shell: "for i in $(KUBECONFIG={{ kubeconfig }} kubectl api-resources | grep chaos-mesh | awk '{print $1}'); do KUBECONFIG={{ kubeconfig }} kubectl delete $i --all -A; done"
  tags:
    - fault_removal
    - chaos_mesh_uninstallation
  when: is_fault_removal | bool

- name: Uninstall Chaos Mesh
  kubernetes.core.helm:
    name: "{{ chaos_mesh_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ chaos_mesh_namespace_project_name }}"
    release_state: absent
  tags:
    - fault_removal
    - chaos_mesh_uninstallation
  when: is_fault_removal | bool

- name: Remove the namespace associated with the Chaos Mesh
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ chaos_mesh_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
  tags:
    - fault_removal
    - chaos_mesh_uninstallation
  when: is_fault_removal | bool
