apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topology-monitor
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
