apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: topology-monitor
subjects:
- kind: ServiceAccount
  name: topology-monitor
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: topology-monitor
  apiGroup: rbac.authorization.k8s.io
