apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: topology-data-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: default