---
- name: Documenting Incident 37
  set_fact:
    all_incidents: "{{ all_incidents + [ docs_incident_37 ] }}"
  tags: documentation, incident_37

- name: Create a HPAs associated with Astronomy Shop deployments
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ item }}"
    namespace: "{{ target_namespace_name }}"
    api_version: autoscaling/v2
    kind: HorizontalPodAutoscaler
    state: present
    resource_definition:
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: "{{ item }}"
        minReplicas: 1
        maxReplicas: 5
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 70
        behavior:
          scaleDown:
            policies:
            - type: Percent
              value: 50
              periodSeconds: 60
            - type: Pods
              value: 2
              periodSeconds: 60
            selectPolicy: Min
    wait: true
  tags: incident_37
  loop: "{{ target_deployments }}"
  when: is_fault_injection | bool

- name: fault_injection_incident_37
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: apps/v1
    kind: Deployment
    name: "{{ otel_astronomy_app_installation_name }}-loadgenerator"
    namespace: "{{ target_namespace_name }}"
    resource_definition:
      spec:
        replicas: 3
    wait: true
  tags: incident_37
  when: is_fault_injection | bool

- name: Scale down load generator
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: apps/v1
    kind: Deployment
    name: "{{ otel_astronomy_app_installation_name }}-loadgenerator"
    namespace: "{{ target_namespace_name }}"
    resource_definition:
      spec:
        replicas: 1
    wait: true
  tags: incident_37
  when: is_fault_removal | bool

- name: Remove the HPA associated with Astronomy Shop recommendation service
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ item }}"
    namespace: "{{ target_namespace_name }}"
    api_version: autoscaling/v2
    kind: HorizontalPodAutoscaler
    state: absent
    wait: true
  tags: incident_37
  loop: "{{ target_deployments }}"
  when: is_fault_removal | bool

- name: fault_removal_incident_37
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: apps/v1
    kind: Deployment
    name: "{{ item }}"
    namespace: "{{ target_namespace_name }}"
    resource_definition:
      spec:
        replicas: 1
    wait: true
  tags: incident_37
  loop: "{{ target_deployments }}"
  when: is_fault_removal | bool
