---
- name: Create empty assertion json
  copy:
    content: "{{ {\"status\": {\"conditions\": []}} | to_json | indent(2) }}"
    dest: "/tmp/assertion.json"
    mode: "0644"
  tags:
    - install_tools
  when:
    - sre_bench_runner

- name: Upload the empty assertion JSON to S3
  amazon.aws.s3_object:
    endpoint_url: "https://s3.us-east-2.amazonaws.com"
    bucket: "{{ s3_bucket_name_for_results }}"
    object: "/{{ sre_agent_name__version_number }}/{{run_uuid}}/{{scenario_number}}/{{run_number}}/assertion.json"
    src: "/tmp/assertion.json"
    mode: put
  tags:
    - install_tools
  when:
    - sre_bench_runner
    - run_uuid is defined and scenario_number is defined and run_number is defined
