---
- name: Add Helm chart repo for Kubernetes Metric Server
  kubernetes.core.helm_repository:
    name: metrics-server
    kubeconfig_path: "{{ kubeconfig }}"
    repo_url: "https://kubernetes-sigs.github.io/metrics-server/"
  tags:
    - install_tools
  when:
    - domain == "finops"

- name: Update Helm repo
  kubernetes.core.helm:
    name: dummy
    kubeconfig_path: "{{ kubeconfig }}"
    state: absent
    release_namespace: "{{ metrics_server_namespace_project_name }}"
    update_repo_cache: true
  tags:
    - install_tools
  when:
    - domain == "finops"

- name: Deploy Kubernetes Metric Server
  kubernetes.core.helm:
    name: "{{ metrics_server_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: metrics-server/metrics-server
    chart_version: "{{ metrics_server_chart_version }}"
    release_namespace: "{{ metrics_server_namespace_project_name }}"
    release_state: present
    create_namespace: true
    wait: true
    timeout: 10m0s
  tags:
    - install_tools
  when:
    - domain == "finops"
