---
- name: Get the Ingress URL of Grafana
  ansible.builtin.shell: "KUBECONFIG={{ kubeconfig }} kubectl get ingress {{ prometheus_namespace_project_name }}-grafana -n {{ prometheus_namespace_project_name }} -o json"
  register: grafana_ingress
  retries: 5
  delay: 60
  until: (grafana_ingress.stdout | length) > 0
  ignore_errors: yes

- name: Extract the Ingress hostname information
  set_fact:
    ingress_hostname: "{{ grafana_ingress.stdout | from_json | json_query('status.loadBalancer.ingress[0].hostname') }}"
  when: grafana_ingress.stdout | trim != ''

- name: Set the Grafana URL
  set_fact:
    grafana_url: "http://{{ ingress_hostname }}/prometheus"
  when: ingress_hostname is defined and ingress_hostname | trim != ''
