- name: Uninstall K8s-Events-Exporter
  kubernetes.core.helm:
    name: "{{ event_exporter_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ loki_namespace_project_name }}"
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"

- name: Uninstall OpenSearch
  kubernetes.core.helm:
    name: "{{ opensearch_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ opensearch_namespace_project_name }}"
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"

- name: Uninstall Jaeger
  kubernetes.core.helm:
    name: "{{ jaeger_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ jaeger_namespace_project_name }}"
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"

- name: Uninstall the Prometheus - Grafana stack
  kubernetes.core.helm:
    name: "{{ prometheus_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ prometheus_namespace_project_name }}"
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"

- name: Uninstall the Kubernetes Metrics Server
  kubernetes.core.helm:
    name: "{{ metrics_server_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ metrics_server_namespace_project_name }}"
    state: absent
  tags:
    - uninstall_tools
  when:
    - domain == "finops"

- name: Uninstall Loki
  kubernetes.core.helm:
    name: "{{ loki_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ loki_namespace_project_name }}"
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"

- name: Uninstall Elasticsearch
  kubernetes.core.helm:
    name: "{{ es_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ es_namespace_project_name }}"
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"

- name: Uninstall OpenCost
  kubernetes.core.helm:
    name: "{{ opencost_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ opencost_namespace_project_name }}"
    state: absent
  tags:
    - uninstall_tools
  when:
    - domain == "finops"

- name: Uninstall Ingress
  kubernetes.core.helm:
    name: "{{ ingress_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ ingress_namespace_project_name }}"
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"

- name: Remove the namespace associated with OpenSearch
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ opensearch_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"

- name: Remove the namespace associated with Jaeger
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ jaeger_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"

- name: Remove the namespace associated with Prometheus
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ prometheus_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"

- name: Remove the namespace associated with Kubernetes Metric Server
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ metrics_server_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "finops"

- name: Remove the namespace associated with Loki
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ loki_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"

- name: Remove the namespace associated with Elasticsearch
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ es_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"

- name: Remove the namespace associated with OpenCost
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ opencost_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "finops"

- name: Remove the namespace associated with Ingress
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ ingress_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"
    - sre_bench_runner
    - run_uuid is defined and scenario_number is defined and run_number is defined

- name: Get the assertion.json from S3
  amazon.aws.s3_object:
    endpoint_url: "https://s3.us-east-2.amazonaws.com"
    bucket: "{{ s3_bucket_name_for_results }}"
    object: "/{{ sre_agent_name__version_number }}/{{run_uuid}}/{{scenario_number}}/{{run_number}}/assertion.json"
    dest: "/tmp/assertion.json"
    mode: get
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"
    - sre_bench_runner
    - run_uuid is defined and scenario_number is defined and run_number is defined

- name: Read deployment and fault injection details from assertion json
  set_fact:
    assertion_array: "{{ lookup('file', '/tmp/assertion.json') | from_json | json_query('status.conditions') }}"
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"
    - sre_bench_runner

- name: Create namespace to delete list
  set_fact:
    namespace_delete_list:
      - "{{ opensearch_namespace_project_name }}"
      - "{{ jaeger_namespace_project_name }}"
      - "{{ loki_namespace_project_name }}"
      - "{{ es_namespace_project_name }}"
      - "{{ prometheus_namespace_project_name }}"
      - "{{ ingress_namespace_project_name }}"
  tags:
    - uninstall_tools

- name: Get all namespaces
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: Namespace
  register: namespaces
  until: "{{ namespaces.resources | json_query('[].metadata.name') | list | intersect(namespace_delete_list) | length < 1 }}"
  retries: 20
  delay: 30
  when:
    - domain == "sre" or domain == "finops"
    - sre_bench_runner
  tags:
    - uninstall_tools

- name: Update assertion array content
  set_fact:
    updated_assertion_array: "{{ assertion_array + [{'type': 'Destroyed', 'status': namespaces.resources | json_query('[].metadata.name') | list | intersect(namespace_delete_list) | length < 1, 'lastTransitionTime':now(utc=True, fmt='%Y-%m-%dT%H:%M:%SZ')}] }}"
  when:
    - domain == "sre" or domain == "finops"
    - sre_bench_runner
  tags:
    - uninstall_tools

- name: Create json structure for assertion json file
  set_fact:
    assertion_json:
      status:
        conditions: "{{ updated_assertion_array }}"
  when:
    - domain == "sre" or domain == "finops"
    - sre_bench_runner
  tags:
    - uninstall_tools

- name: Update assertion json file
  copy:
    content: "{{ assertion_json | to_json | indent(2) }}"
    dest: "/tmp/assertion.json"
    mode: "0644"
  when:
    - domain == "sre" or domain == "finops"
    - sre_bench_runner
  tags:
    - uninstall_tools

- name: Upload the assertion JSON to S3
  amazon.aws.s3_object:
    endpoint_url: "https://s3.us-east-2.amazonaws.com"
    bucket: "{{ s3_bucket_name_for_results }}"
    object: "/{{ sre_agent_name__version_number }}/{{run_uuid}}/{{scenario_number}}/{{run_number}}/assertion.json"
    src: "/tmp/assertion.json"
    mode: put
  tags:
    - uninstall_tools
  when:
    - domain == "sre" or domain == "finops"
    - sre_bench_runner
    - run_uuid is defined and scenario_number is defined and run_number is defined
