---
- name: Show values
  debug:
    msg: 
      - "{{ kops_path }}"
      - "{{ state_store }}"
      - "{{ cluster_batch }}"

- name: Build clusters concurrently
  command: >
    {{ kops_path }} update cluster
    --name {{ item }}
    --state={{ state_store }}
    --yes
    --internal
    --create-kube-config=false
  loop: "{{ cluster_batch }}"
  register: build_tasks
  async: 1800
  poll: 0

- name: Wait for cluster builds to complete
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: build_tasks_status
  until: build_tasks_status.finished
  retries: 30
  delay: 60
  loop: "{{ build_tasks.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Show build status
  debug:
    msg: 
      - "Build status for cluster {{ item.item }}:"
      - "{{ item.stdout_lines | default([]) }}"
  loop: "{{ build_tasks_status.results }}"
  when: build_tasks_status is defined
