---
- hosts: localhost
  vars:
    state_store: "s3://{{ s3name }}"
  vars_files:
    - variables.yaml
    - secret.yaml
  gather_facts: true
  vars_prompt:
    - name: "control_node_count"
      prompt: "Number of control plane nodes. Must be an odd number. On entering a number less than 1 cluster creation will be aborted."
      private: no

    - name: "inp"
      prompt: "On entering a number (less than 10), cluster with that many worker nodes will be created. Else cluster creation will be aborted"
      private: no

    - name: "cluster_name"
      prompt: "provide the partial cluster identifier"
      private: no

    - name: "instance_type"
      prompt: "provide the instance type (m4.large, m4.xlarge, ...)"
      private: no
  tasks:
    - name: Set kops path for Linux
      set_fact:
        kops_path: "/usr/local/bin/kops"
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      
    - name: Set kops path for macOS
      set_fact:
        kops_path: "{{ '/opt/homebrew/bin/kops' if ansible_architecture == 'arm64' else '/usr/local/bin/kops' }}"
      when: ansible_distribution == 'MacOSX'

    - name: Number of control plane nodes
      fail:
        msg: "ERROR: Entered - {{ control_node_count }} - Not a number for number of control plane nodes."
      when: control_node_count is not number and control_node_count | int == 0

    - name: Number of worker nodes
      fail:
        msg: "ERROR: Entered - {{ inp }} - Not a number for number of nodes."
      when: inp is not number and inp | int == 0

    - name: Validate input is less than 10
      fail:
        msg: "ERROR: Tried to create more than 10 nodes. Not allowing!"
      when: inp | int >= 10

    - name: Create kops cluster
      command: 
        cmd:
          "{{ kops_path }} create cluster {{ cluster_name }}-{{ instance_type }}-aws.k8s.local \
          --zones {{ zones }} \
          --ssh-public-key {{ ssh_key_for_cluster }} \
          --control-plane-size {{ control_node_type }} \
          --control-plane-count {{ control_node_count }} \
          --node-size {{ instance_type }} \
          --node-count {{ inp }} \
          --networking {{ network_cni }} \
          --state={{ state_store }} "

    - name: Build the Cluster
      command:
        cmd: "{{ kops_path }} update cluster --name={{ cluster_name }}-{{ instance_type }}-aws.k8s.local --state={{ state_store }} --yes --internal"
      register: kops_output

    - name: Display kops logs
      debug:
        msg: "{{ kops_output.stdout_lines }}"

    - name: "export kubeconfig"
      shell: "{{ kops_path }} export --name {{ cluster_name }}-{{ instance_type }}-aws.k8s.local kubecfg --admin --state s3://{{ s3name }} --kubeconfig /tmp/{{ cluster_name }}-{{ instance_type }}-aws.yaml"

    - name: Validate the cluster
      command: "{{ kops_path }} validate cluster --state={{ state_store }}"
      environment:
        KUBECONFIG: /tmp/{{ cluster_name }}-{{ instance_type }}-aws.yaml
      register: validate_output
      # ignore_errors: true
      retries: 60
      delay: 10
      until: "'is ready' in validate_output.stdout"

    - name: Pause and prompt user if validation fails
      pause:
        prompt: "Cluster validation failed. Please manually check the cluster status and press enter to continue.  Run {{ kops_path }} export --name {{ cluster_name }}-{{ instance_type }}-aws.k8s.local kubecfg --admin --state s3://{{ s3name }} --kubeconfig /tmp/{{ cluster_name }}-{{ instance_type }}-aws.yaml && {{ kops_path }} validate cluster --state={{ state_store }}"
      when: "validate_output.stdout is not defined or 'is ready' not in validate_output.stdout"

    - name: Debug validate_output
      debug:
        var: validate_output

    - name: Show Additional Instructions
      debug:
        msg:
          - "You can ssh into any of the machines in the cluster, using {{ ssh_key_for_cluster }}."
          - "You can destroy the cluster by running kops delete cluster --name <cluster_name> --yes."
