---
- name: Delete All Kubernetes Clusters Managed by kops
  hosts: localhost
  vars_files:
    - variables.yaml
    - secret.yaml
  gather_facts: true
  tasks:
    - name: Set kops path for Linux
      set_fact:
        kops_path: "/usr/local/bin/kops"
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - name: Set kops path for macOS
      set_fact:
        kops_path: "{{ '/opt/homebrew/bin/kops' if ansible_architecture == 'arm64' else '/usr/local/bin/kops' }}"
      when: ansible_distribution == 'MacOSX'

    - name: Fetch list of all kops clusters
      command:
        cmd: "{{ kops_path }} get clusters --output json --state s3://{{ s3name }}"
      register: cluster_list_output
      ignore_errors: true

    - name: Check if no clusters are found
      meta: end_play
      when: "'Error: no clusters found' in cluster_list_output.stderr or 'Error: no clusters found' in cluster_list_output.stdout"

    - name: Parse JSON output to list of cluster names
      set_fact:
        cluster_names: "{{ cluster_list_output.stdout | from_json | map(attribute='metadata.name') | list }}"
      when: cluster_list_output.stdout != ""

    - name: Confirm deletion of all clusters
      pause:
        prompt: "Are you sure you want to delete ALL clusters {{ cluster_names }}? (Press enter to continue or Ctrl+C to abort)"
      when: cluster_list_output.stdout != ""

    - name: Delete kops clusters
      command:
        cmd: "{{ kops_path }} delete cluster --name={{ item }} --yes --state s3://{{ s3name }}"
      loop: "{{ cluster_names }}"
      when: cluster_names is defined
