---
- name: Check availability of ports
  ansible.builtin.shell: |
    lsof -i :{{ item }} > /dev/null && echo "in_use" || echo "available"
  register: lsof_check
  loop: "{{ range(32100, 32125) | list }}"  
  changed_when: false
  failed_when: false
  loop_control:
    loop_var: item
  when: ingress_hostname is undefined or ingress_hostname | trim == ''

- name: Assign a dynamic port if one is available
  set_fact:
    dynamic_port: "{{ (lsof_check.results | selectattr('stdout', 'equalto', 'available') | map(attribute='item') | list | first) }}"
  when: ingress_hostname is undefined or ingress_hostname | trim == ''

- name: Kubectl port-forward on/for the Topology Monitor
  ansible.builtin.shell: KUBECONFIG={{ kubeconfig }} kubectl -n kube-system port-forward "svc/topology-monitor" "{{ dynamic_port }}:8080" --request-timeout=15m
  async: 900
  poll: 0
  register: grafana_port_forward_for_topology_collection_post_fault_injection
  when: ingress_hostname is undefined or ingress_hostname | trim == ''

- name: Wait for port-forward to be available
  ansible.builtin.wait_for_connection:
    delay: 5
    timeout: 30
  when: ingress_hostname is undefined or ingress_hostname | trim == ''

- name: Set the Grafana URL
  set_fact:
    topology_url: "http://127.0.0.1:{{ dynamic_port }}"
  when: ingress_hostname is undefined or ingress_hostname | trim == ''
